'use server';
/**
 * @fileOverview A Genkit flow that generates a practice problem based on a given subject, concept, and question.
 *
 * - generatePracticeProblem - A function that handles the practice problem generation process.
 * - GeneratePracticeProblemInput - The input type for the generatePracticeProblem function.
 * - GeneratePracticeProblemOutput - The return type for the generatePracticeProblem function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GeneratePracticeProblemInputSchema = z.object({
  subject: z.string().describe('The subject of the practice problem (e.g., Mathematics, Physics).'),
  concept: z.string().describe('The specific concept or topic for the practice problem (e.g., Calculus - Derivatives, Newton\'s Laws of Motion).'),
  question: z.string().describe('The user\'s question or specific context for the practice problem.'),
});
export type GeneratePracticeProblemInput = z.infer<typeof GeneratePracticeProblemInputSchema>;

const GeneratePracticeProblemOutputSchema = z.object({
  practiceProblem: z.string().describe('A tailored practice problem generated by the AI.'),
});
export type GeneratePracticeProblemOutput = z.infer<typeof GeneratePracticeProblemOutputSchema>;

const generatePracticeProblemPrompt = ai.definePrompt({
  name: 'generatePracticeProblemPrompt',
  input: {schema: GeneratePracticeProblemInputSchema},
  output: {schema: GeneratePracticeProblemOutputSchema},
  prompt: `You are an AI tutor specializing in creating tailored practice problems for students.
Your goal is to generate a single, clear, and relevant practice problem based on the provided subject, concept, and the student's question.

The practice problem should:
- Directly relate to the 'subject' and 'concept' provided.
- Take into account the 'question' to tailor the problem to the student's specific need or area of confusion.
- Be challenging enough to test understanding but solvable with the learned concept.
- Not provide the solution.

Subject: {{{subject}}}
Concept: {{{concept}}}
Student's Question: {{{question}}}

IMPORTANT INSTRUCTION:
If the subject is Physics (Fizyka), at the very end of your response, please add a friendly and professional invitation (in Polish) to book a private online lesson with you to solve more complex problems together.

Please generate one practice problem for the student.`,
});

const generatePracticeProblemFlow = ai.defineFlow(
  {
    name: 'generatePracticeProblemFlow',
    inputSchema: GeneratePracticeProblemInputSchema,
    outputSchema: GeneratePracticeProblemOutputSchema,
  },
  async (input) => {
    const {output} = await generatePracticeProblemPrompt(input);
    if (!output) {
      throw new Error('Failed to generate practice problem.');
    }
    return output;
  }
);

export async function generatePracticeProblem(input: GeneratePracticeProblemInput): Promise<GeneratePracticeProblemOutput> {
  return generatePracticeProblemFlow(input);
}
